# -*- coding: utf-8 -*-
"""Tugas1_IntegritasSistem_Doni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8qOAbAMqHA5r8_2-3Q_H3iM917lF-Xj
"""

import requests
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Function to fetch data
def fetch_data():
    body = {"locations": [[9.70093, 48.477473], [9.207916, 49.153868], [37.573242, 55.801281], [115.663757, 38.106467]]}
    headers = {
        'Accept': 'application/json, application/geo+json, application/gpx+xml, img/png; charset=utf-8',
        'Authorization': '5b3ce3597851110001cf6248a3356a672eab4600adb2ca42d468ad95',
        'Content-Type': 'application/json; charset=utf-8'
    }
    response = requests.post('https://api.openrouteservice.org/v2/matrix/driving-car', json=body, headers=headers)

    if response.status_code == 200:
        return response.json()
    else:
        return None

# Function to display data in a DataFrame
def display_data(_):
    data = fetch_data()
    if data:
        durations = data.get("durations", [])
        df = pd.DataFrame(durations, columns=["Location 1", "Location 2", "Location 3", "Location 4"],
                           index=["Location 1", "Location 2", "Location 3", "Location 4"])
        display(df)
    else:
        print("Failed to fetch data")

# Button to fetch and display data
fetch_button = widgets.Button(description="Fetch Data")
fetch_button.on_click(display_data)
display(fetch_button)